name: 功能建议
description: 描述实际使用问题和屏幕空间需求
body:
  - type: textarea
    id: scenario
    attributes:
      label: 使用场景与目前不方便之处
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 方案与取舍
      description: 是否增加联网／耗电，屏幕放在哪里，如何避免配置复杂
