"""Generate the small subject-only 22px bitmap font used on the e-paper page.

The source is the locally installed Noto Sans SC variable font. Only glyphs
used by the built-in timetable are embedded; arbitrary course names fall back
to the existing U8g2 Chinese font at runtime.
"""

from pathlib import Path
import argparse
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--font", type=Path, required=True, help="Path to Noto Sans SC variable TTF")
FONT = parser.parse_args().font
GLYPHS = "地理数学语文英化物班会自习体育社团周考放假待配置日休息今天/"
HEIGHT = 24

font = ImageFont.truetype(str(FONT), 21)
font.set_variation_by_name("Bold")

records = []
for char in dict.fromkeys(GLYPHS):
    width = 11 if char == "/" else 22
    canvas = Image.new("1", (width, HEIGHT), 0)
    draw = ImageDraw.Draw(canvas)
    draw.text((width / 2, HEIGHT / 2), char, font=font, anchor="mm", fill=1)
    bits = []
    for y in range(HEIGHT):
        for x in range(width):
            bits.append(1 if canvas.getpixel((x, y)) else 0)
    data = []
    for i in range(0, len(bits), 8):
        byte = sum(bit << (7 - j) for j, bit in enumerate(bits[i:i + 8]))
        data.append(byte)
    records.append((ord(char), width, data))

lines = [
    "// Generated by tools/generate_subject_font.py from Noto Sans SC Bold.",
    "// The source font is licensed under the SIL Open Font License.",
    "#ifndef SUBJECT_FONT_H",
    "#define SUBJECT_FONT_H",
    "#include <Arduino.h>",
    "struct SubjectGlyph { uint32_t codepoint; uint8_t width; uint8_t pixels[66]; };",
    "static const SubjectGlyph SUBJECT_GLYPHS[] PROGMEM = {",
]
for codepoint, width, data in records:
    assert len(data) <= 66
    padded = data + [0] * (66 - len(data))
    lines.append("    {0x%04X, %d, {%s}}," % (
        codepoint, width, ", ".join("0x%02X" % byte for byte in padded)
    ))
lines += [
    "};",
    "static const int SUBJECT_GLYPH_COUNT = sizeof(SUBJECT_GLYPHS) / sizeof(SUBJECT_GLYPHS[0]);",
    "#endif",
]
(ROOT / "include" / "subject_font.h").write_text("\n".join(lines) + "\n", encoding="utf-8")
